### ISSUE TITLE
Crashes / Hangs when pressing open after some times

### ISSUE THREAD

**Issue by khaled-0** [taunoe/tauno-monitor#5]
It works fine but 
I have to disconnect before flashing my device
then when I press connect again, it hangs leading to crash.

But I can open and close before flashing without crash

Using Flathub version on Fedora 39

**Comment by taunoe** [comment]
For flashing you use a separate app?

**Comment by khaled-0** [comment]
> For flashing you use a separate app?

Yeah I use platformio in vscode. which calls ``platformio run --target upload``

**Comment by taunoe** [comment]
There can't be multiple access on the same port.
After that, the port name is changed. So no easy reconnection. The only thing that I can do is to close the serial port properly and the user can manually make a new connection.

**Comment by khaled-0** [comment]
I close the connection manually before flashing. so it's unlikely it'll fix the issue.
but I'll report back after I test.

**Comment by taunoe** [comment]
What happens if you rescan ports before reopening?

**Comment by khaled-0** [comment]
After 1.9.10 update
```
Open: /dev/ttyUSB0 9600
Opened successfully
Close: /dev/ttyUSB0 9600
Serial read error:  read failed: [Errno 9] Bad file descriptor
Close: /dev/ttyUSB0 9600
Exception in thread Thread-1 (read):
Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/serial/serialposix.py", line 565, in read
    ready, _, _ = select.select([self.fd, self.pipe_abort_read_r], [], [], timeout.time_left())
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/share/tauno-monitor/tauno_monitor/window.py", line 352, in read
    data_in = self.myserial.read()  # read a byte
              ^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/serial/serialposix.py", line 581, in read
Closed successfully
    raise SerialException('read failed: {}'.format(e))
serial.serialutil.SerialException: read failed: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/app/share/tauno-monitor/tauno_monitor/window.py", line 358, in read
    self.window_reference.close_if_error(self.myserial.port, self.myserial.baudrate)
  File "/app/share/tauno-monitor/tauno_monitor/window.py", line 255, in close_if_error
    self.tauno_serial.close()
  File "/app/share/tauno-monitor/tauno_monitor/window.py", line 340, in close
    self.myserial.close()
  File "/app/lib/python3.11/site-packages/serial/serialposix.py", line 533, in close
    os.close(self.fd)
OSError: [Errno 9] Bad file descriptor
```

https://github.com/taunoe/tauno-monitor/assets/74397286/356498e4-2bbb-48ba-8c3e-ded9e2cae3c4

Behavior with CuteCom:
https://github.com/taunoe/tauno-monitor/assets/74397286/dd97f301-3792-4ec3-af4c-11908ca9bc42

**Comment by khaled-0** [comment]
It shouldn't crash if the serial port gets spammed though.
But I believe the original issue is fixed, As it doesn't crash even after reconnection

CuteCom seems to perform a reset action when opening 
And I don't see crash either if I reset just at the time of opening a connection.

**Comment by khaled-0** [comment]
Idk but the problem seems to no longer happen in v1.10
I'll close this issue for now. Thanks for the time and efforts you put into this.
